total_amount = (67)
quarters = (amount/25)
amount = (amount%25)
dimes = (amount/10)
amount=(amount%10)
nickles = (amount/5)
amount = (amount%5)
print ("Quarters: ", quarters)
print ("Dimes: ", dimes)
print ("Nickels: ", nickles)
print ("Pennies: ", amount)
